import type { Card, Difficulty, Genre } from '@/game/types';

/**
 * The card catalogue.
 *
 * Every year here is the year of **first commercial release**, checked by hand.
 * This is not a detail: Spotify reports the date of whichever master it is
 * serving, so `album.release_date` says 2011 for Bohemian Rhapsody and 2015 for
 * half of Motown. Dating songs *is* the game, so the years cannot come from the
 * API — they are curated, and the Spotify catalogue is only ever used to find
 * something to play.
 *
 * Difficulty describes how hard the track is to **date**, not how obscure it is.
 * A `hard` card is one the whole table can sing and nobody can place: Indeep,
 * Alphaville, Desireless. Those are the cards that make the game funny, so the
 * deck builder deliberately sprinkles them in rather than shuffling flat.
 *
 * Rows are compact on purpose — they are read and edited far more often than
 * they are executed.
 */

type Row = [
  title: string,
  artist: string,
  year: number,
  genres: string,
  difficulty?: 'e' | 'm' | 'h',
];

const DIFFICULTY: Record<'e' | 'm' | 'h', Difficulty> = {
  e: 'easy',
  m: 'medium',
  h: 'hard',
};

const ROWS: Row[] = [
  // ---------------------------------------------------------------- 1940–1959
  ['La Mer', 'Charles Trenet', 1946, 'chanson', 'm'],
  ['La Vie en rose', 'Édith Piaf', 1947, 'chanson', 'm'],
  ['Les Feuilles mortes', 'Yves Montand', 1949, 'chanson', 'm'],
  ['Unforgettable', 'Nat King Cole', 1951, 'pop', 'm'],
  ['Petite Fleur', 'Sidney Bechet', 1952, 'pop', 'h'],
  ["That's Amore", 'Dean Martin', 1953, 'pop', 'm'],
  ['Rock Around the Clock', 'Bill Haley & His Comets', 1954, 'rock', 'e'],
  ['Le Déserteur', 'Boris Vian', 1954, 'chanson', 'm'],
  ['Maybellene', 'Chuck Berry', 1955, 'rock', 'm'],
  ['Tutti Frutti', 'Little Richard', 1955, 'rock', 'm'],
  ['Only You', 'The Platters', 1955, 'pop', 'm'],
  ['Roll Over Beethoven', 'Chuck Berry', 1956, 'rock', 'm'],
  ['Bambino', 'Dalida', 1956, 'chanson', 'm'],
  ['Heartbreak Hotel', 'Elvis Presley', 1956, 'rock', 'e'],
  ['Hound Dog', 'Elvis Presley', 1956, 'rock', 'e'],
  ["Quand on n'a que l'amour", 'Jacques Brel', 1956, 'chanson', 'm'],
  ['Jailhouse Rock', 'Elvis Presley', 1957, 'rock', 'e'],
  ['Great Balls of Fire', 'Jerry Lee Lewis', 1957, 'rock', 'm'],
  ["That'll Be the Day", 'Buddy Holly', 1957, 'rock', 'm'],
  ['Bye Bye Love', 'The Everly Brothers', 1957, 'rock', 'h'],
  ['Johnny B. Goode', 'Chuck Berry', 1958, 'rock', 'e'],
  ['La Bamba', 'Ritchie Valens', 1958, 'rock', 'm'],
  ['Mack the Knife', 'Bobby Darin', 1959, 'pop', 'h'],
  ["Ne me quitte pas", 'Jacques Brel', 1959, 'chanson', 'e'],
  ["What'd I Say", 'Ray Charles', 1959, 'funk', 'm'],

  // ---------------------------------------------------------------- 1960–1969
  ["Je m'voyais déjà", 'Charles Aznavour', 1960, 'chanson', 'm'],
  ['Non, je ne regrette rien', 'Édith Piaf', 1960, 'chanson', 'e'],
  ['Stand by Me', 'Ben E. King', 1961, 'funk', 'e'],
  ["Can't Help Falling in Love", 'Elvis Presley', 1961, 'pop', 'e'],
  ["L'école est finie", 'Sheila', 1963, 'chanson', 'h'],
  ["Surfin' U.S.A.", 'The Beach Boys', 1963, 'rock', 'm'],
  ['Tombe la neige', 'Salvatore Adamo', 1963, 'chanson', 'm'],
  ['La Javanaise', 'Serge Gainsbourg', 1963, 'chanson', 'm'],
  ['She Loves You', 'The Beatles', 1963, 'rock', 'm'],
  ['Twist and Shout', 'The Beatles', 1963, 'rock', 'e'],
  ['Göttingen', 'Barbara', 1964, 'chanson', 'h'],
  ['Fly Me to the Moon', 'Frank Sinatra', 1964, 'pop', 'h'],
  ['Nathalie', 'Gilbert Bécaud', 1964, 'chanson', 'h'],
  ['Amsterdam', 'Jacques Brel', 1964, 'chanson', 'm'],
  ["A Hard Day's Night", 'The Beatles', 1964, 'rock', 'm'],
  ["Les Copains d'abord", 'Georges Brassens', 1964, 'chanson', 'm'],
  ['Oh, Pretty Woman', 'Roy Orbison', 1964, 'rock', 'm'],
  ['A Change Is Gonna Come', 'Sam Cooke', 1964, 'funk', 'h'],
  ['The House of the Rising Sun', 'The Animals', 1964, 'rock', 'm'],
  ['You Really Got Me', 'The Kinks', 1964, 'rock', 'm'],
  ['My Girl', 'The Temptations', 1964, 'funk', 'e'],
  ['Like a Rolling Stone', 'Bob Dylan', 1965, 'rock', 'm'],
  ['La Bohème', 'Charles Aznavour', 1965, 'chanson', 'm'],
  ["(I Can't Get No) Satisfaction", 'The Rolling Stones', 1965, 'rock', 'e'],
  ['Poupée de cire, poupée de son', 'France Gall', 1965, 'chanson', 'm'],
  ["It's Not Unusual", 'Tom Jones', 1965, 'pop', 'h'],
  ['I Got You (I Feel Good)', 'James Brown', 1965, 'funk', 'e'],
  ["California Dreamin'", 'The Mamas & The Papas', 1965, 'pop', 'm'],
  ['Feeling Good', 'Nina Simone', 1965, 'funk', 'h'],
  ['The Sound of Silence', 'Simon & Garfunkel', 1965, 'pop', 'm'],
  ['Mr. Tambourine Man', 'The Byrds', 1965, 'rock', 'h'],
  ['Unchained Melody', 'The Righteous Brothers', 1965, 'pop', 'h'],
  ['My Generation', 'The Who', 1965, 'rock', 'm'],
  ['Les Élucubrations', 'Antoine', 1966, 'chanson', 'h'],
  ["I'm a Believer", 'The Monkees', 1966, 'pop', 'h'],
  ['River Deep – Mountain High', 'Ike & Tina Turner', 1966, 'funk', 'h'],
  ['Et moi, et moi, et moi', 'Jacques Dutronc', 1966, 'chanson', 'm'],
  ["You Can't Hurry Love", 'The Supremes', 1966, 'funk', 'm'],
  ['Love Me, Please Love Me', 'Michel Polnareff', 1966, 'chanson', 'm'],
  ['These Boots Are Made for Walkin’', 'Nancy Sinatra', 1966, 'pop', 'm'],
  ['Mirza', 'Nino Ferrer', 1966, 'chanson', 'h'],
  ['Try a Little Tenderness', 'Otis Redding', 1966, 'funk', 'h'],
  ['When a Man Loves a Woman', 'Percy Sledge', 1966, 'funk', 'm'],
  ['Good Vibrations', 'The Beach Boys', 1966, 'pop', 'm'],
  ['Hey Joe', 'The Jimi Hendrix Experience', 1966, 'rock', 'm'],
  ['Paint It, Black', 'The Rolling Stones', 1966, 'rock', 'm'],
  ['Land of 1000 Dances', 'Wilson Pickett', 1966, 'funk', 'h'],
  ['Respect', 'Aretha Franklin', 1967, 'funk', 'e'],
  ['Toulouse', 'Claude Nougaro', 1967, 'chanson', 'h'],
  ['Sunshine of Your Love', 'Cream', 1967, 'rock', 'h'],
  ['What a Wonderful World', 'Louis Armstrong', 1967, 'pop', 'e'],
  ["Ain't No Mountain High Enough", 'Marvin Gaye & Tammi Terrell', 1967, 'funk', 'm'],
  ["Comme d'habitude", 'Claude François', 1967, 'chanson', 'm'],
  ['A Whiter Shade of Pale', 'Procol Harum', 1967, 'rock', 'h'],
  ['Soul Man', 'Sam & Dave', 1967, 'funk', 'h'],
  ['San Francisco (Be Sure to Wear Flowers in Your Hair)', 'Scott McKenzie', 1967, 'pop', 'm'],
  ['Light My Fire', 'The Doors', 1967, 'rock', 'm'],
  ['Purple Haze', 'The Jimi Hendrix Experience', 1967, 'rock', 'm'],
  ['Happy Together', 'The Turtles', 1967, 'pop', 'h'],
  ['Israelites', 'Desmond Dekker & The Aces', 1968, 'reggae', 'h'],
  ['Son of a Preacher Man', 'Dusty Springfield', 1968, 'funk', 'h'],
  ["Il est cinq heures, Paris s'éveille", 'Jacques Dutronc', 1968, 'chanson', 'm'],
  ['I Heard It Through the Grapevine', 'Marvin Gaye', 1968, 'funk', 'm'],
  ['(Sittin’ On) The Dock of the Bay', 'Otis Redding', 1968, 'funk', 'm'],
  ['Bonnie and Clyde', 'Serge Gainsbourg', 1968, 'chanson', 'h'],
  ['Requiem pour un con', 'Serge Gainsbourg', 1968, 'chanson', 'h'],
  ['Mrs. Robinson', 'Simon & Garfunkel', 1968, 'pop', 'm'],
  ['Hey Jude', 'The Beatles', 1968, 'rock', 'e'],
  ['Sympathy for the Devil', 'The Rolling Stones', 1968, 'rock', 'm'],
  ['Fortunate Son', 'Creedence Clearwater Revival', 1969, 'rock', 'm'],
  ['Les Champs-Élysées', 'Joe Dassin', 1969, 'chanson', 'm'],
  ['Whole Lotta Love', 'Led Zeppelin', 1969, 'rock', 'm'],
  ["Je t'aime… moi non plus", 'Serge Gainsbourg', 1969, 'chanson', 'm'],
  ["Que je t'aime", 'Johnny Hallyday', 1969, 'chanson', 'm'],
  ['Wight Is Wight', 'Michel Delpech', 1969, 'chanson', 'h'],
  ['Come Together', 'The Beatles', 1969, 'rock', 'm'],
  ['I Want You Back', 'The Jackson 5', 1969, 'funk', 'm'],

  // ---------------------------------------------------------------- 1970–1979
  ['Paranoid', 'Black Sabbath', 1970, 'metal', 'm'],
  ['Your Song', 'Elton John', 1970, 'pop', 'm'],
  ['Avec le temps', 'Léo Ferré', 1970, 'chanson', 'm'],
  ["L'Aigle noir", 'Barbara', 1970, 'chanson', 'm'],
  ['Let It Be', 'The Beatles', 1970, 'rock', 'e'],
  ['Life on Mars?', 'David Bowie', 1971, 'rock', 'h'],
  ['Imagine', 'John Lennon', 1971, 'pop', 'e'],
  ['Stairway to Heaven', 'Led Zeppelin', 1971, 'rock', 'e'],
  ["Ain't No Sunshine", 'Bill Withers', 1971, 'funk', 'm'],
  ["What's Going On", 'Marvin Gaye', 1971, 'funk', 'm'],
  ['Smoke on the Water', 'Deep Purple', 1972, 'rock', 'm'],
  ['Rocket Man', 'Elton John', 1972, 'pop', 'm'],
  ['You Can Get It If You Really Want', 'Jimmy Cliff', 1972, 'reggae', 'h'],
  ['Superstition', 'Stevie Wonder', 1972, 'funk', 'm'],
  ['Amoureuse', 'Véronique Sanson', 1972, 'chanson', 'h'],
  ['Money', 'Pink Floyd', 1973, 'rock', 'm'],
  ['The Joker', 'Steve Miller Band', 1973, 'rock', 'h'],
  ['Live and Let Die', 'Wings', 1973, 'rock', 'h'],
  ['Waterloo', 'ABBA', 1974, 'pop', 'e'],
  ['No Woman, No Cry', 'Bob Marley & The Wailers', 1974, 'reggae', 'e'],
  ['Kung Fu Fighting', 'Carl Douglas', 1974, 'funk', 'h'],
  ["Gigi l'Amoroso", 'Dalida', 1974, 'chanson', 'h'],
  ['Sweet Home Alabama', 'Lynyrd Skynyrd', 1974, 'rock', 'm'],
  ["You're the First, the Last, My Everything", 'Barry White', 1974, 'funk', 'm'],
  ["L'Été indien", 'Joe Dassin', 1975, 'chanson', 'm'],
  ['Le Sud', 'Nino Ferrer', 1975, 'chanson', 'm'],
  ['Bohemian Rhapsody', 'Queen', 1975, 'rock', 'e'],
  ['Dancing Queen', 'ABBA', 1976, 'pop', 'e'],
  ['Gonna Fly Now (Theme from Rocky)', 'Bill Conti', 1976, 'ost', 'm'],
  ['Daddy Cool', 'Boney M.', 1976, 'funk', 'h'],
  ['Hotel California', 'Eagles', 1976, 'rock', 'e'],
  ['Legalize It', 'Peter Tosh', 1976, 'reggae', 'h'],
  ['Blitzkrieg Bop', 'Ramones', 1976, 'rock', 'm'],
  ['Anarchy in the U.K.', 'Sex Pistols', 1976, 'rock', 'm'],
  ['Disco Inferno', 'The Trammps', 1976, 'funk', 'h'],
  ['Night Fever', 'Bee Gees', 1977, 'funk', 'm'],
  ['Lovely Day', 'Bill Withers', 1977, 'funk', 'h'],
  ['Jamming', 'Bob Marley & The Wailers', 1977, 'reggae', 'm'],
  ['Three Little Birds', 'Bob Marley & The Wailers', 1977, 'reggae', 'm'],
  ['Supernature', 'Cerrone', 1977, 'electro', 'h'],
  ['Heroes', 'David Bowie', 1977, 'rock', 'm'],
  ['I Feel Love', 'Donna Summer', 1977, 'electro', 'h'],
  ["Stayin' Alive", 'Bee Gees', 1977, 'funk', 'e'],
  ['Dreams', 'Fleetwood Mac', 1977, 'rock', 'm'],
  ['Main Title (Star Wars)', 'John Williams', 1977, 'ost', 'e'],
  ['Ça plane pour moi', 'Plastic Bertrand', 1977, 'rock', 'h'],
  ['Heart of Glass', 'Blondie', 1978, 'pop', 'm'],
  ['Is This Love', 'Bob Marley & The Wailers', 1978, 'reggae', 'm'],
  ['Rasputin', 'Boney M.', 1978, 'funk', 'h'],
  ['Le Freak', 'Chic', 1978, 'funk', 'm'],
  ['Alexandrie Alexandra', 'Claude François', 1978, 'chanson', 'm'],
  ['Le Chanteur', 'Daniel Balavoine', 1978, 'chanson', 'm'],
  ['September', 'Earth, Wind & Fire', 1978, 'funk', 'e'],
  ['I Will Survive', 'Gloria Gaynor', 1978, 'funk', 'e'],
  ["Da Ya Think I'm Sexy?", 'Rod Stewart', 1978, 'funk', 'h'],
  ['Roxanne', 'The Police', 1978, 'rock', 'm'],
  ['Y.M.C.A.', 'Village People', 1978, 'funk', 'e'],
  ['Gimme! Gimme! Gimme! (A Man After Midnight)', 'ABBA', 1979, 'pop', 'm'],
  ['Highway to Hell', 'AC/DC', 1979, 'rock', 'e'],
  ['Ring My Bell', 'Anita Ward', 1979, 'funk', 'h'],
  ["Ladies' Night", 'Kool & The Gang', 1979, 'funk', 'h'],
  ["Boys Don't Cry", 'The Cure', 1979, 'rock', 'm'],
  ["Don't Stop 'Til You Get Enough", 'Michael Jackson', 1979, 'funk', 'm'],
  ["Je l'aime à mourir", 'Francis Cabrel', 1979, 'chanson', 'm'],
  ['Born to Be Alive', 'Patrick Hernandez', 1979, 'funk', 'h'],
  ['Another Brick in the Wall, Pt. 2', 'Pink Floyd', 1979, 'rock', 'e'],
  ['We Are Family', 'Sister Sledge', 1979, 'funk', 'm'],
  ['The Logical Song', 'Supertramp', 1979, 'rock', 'h'],
  ['My Sharona', 'The Knack', 1979, 'rock', 'h'],

  // ---------------------------------------------------------------- 1980–1989
  ['Back in Black', 'AC/DC', 1980, 'rock', 'e'],
  ['Call Me', 'Blondie', 1980, 'pop', 'm'],
  ['Could You Be Loved', 'Bob Marley & The Wailers', 1980, 'reggae', 'm'],
  ['Love Will Tear Us Apart', 'Joy Division', 1980, 'rock', 'm'],
  ['Breaking the Law', 'Judas Priest', 1980, 'metal', 'h'],
  ['Celebration', 'Kool & The Gang', 1980, 'funk', 'm'],
  ['Amoureux solitaires', 'Lio', 1980, 'chanson', 'h'],
  ['Ace of Spades', 'Motörhead', 1980, 'metal', 'm'],
  ['Crazy Train', 'Ozzy Osbourne', 1980, 'metal', 'm'],
  ['Another One Bites the Dust', 'Queen', 1980, 'rock', 'e'],
  ['Once in a Lifetime', 'Talking Heads', 1980, 'rock', 'h'],
  ['Résiste', 'France Gall', 1981, 'chanson', 'm'],
  ["Just Can't Get Enough", 'Depeche Mode', 1981, 'electro', 'h'],
  ["Don't Stop Believin'", 'Journey', 1981, 'rock', 'm'],
  ['Les Lacs du Connemara', 'Michel Sardou', 1981, 'chanson', 'e'],
  ['Under Pressure', 'Queen & David Bowie', 1981, 'rock', 'm'],
  ['Chariots of Fire', 'Vangelis', 1981, 'ost', 'm'],
  ['Maneater', 'Daryl Hall & John Oates', 1982, 'pop', 'h'],
  ['Rio', 'Duran Duran', 1982, 'pop', 'm'],
  ["Don't Go", 'Yazoo', 1982, 'electro', 'h'],
  ['Last Night a D.J. Saved My Life', 'Indeep', 1982, 'funk', 'h'],
  ['Comme toi', 'Jean-Jacques Goldman', 1982, 'chanson', 'm'],
  ['Femmes je vous aime', 'Julien Clerc', 1982, 'chanson', 'h'],
  ["L'Aventurier", 'Indochine', 1982, 'rock', 'm'],
  ['Beat It', 'Michael Jackson', 1982, 'pop', 'e'],
  ['Billie Jean', 'Michael Jackson', 1982, 'pop', 'e'],
  ['Thriller', 'Michael Jackson', 1982, 'pop', 'e'],
  ['Eye of the Tiger', 'Survivor', 1982, 'rock', 'e'],
  ['Africa', 'Toto', 1982, 'rock', 'e'],
  ['Da Da Da', 'Trio', 1982, 'electro', 'h'],
  ['Cendrillon', 'Téléphone', 1982, 'rock', 'm'],
  ['Brigadier Sabari', 'Alpha Blondy', 1983, 'reggae', 'h'],
  ['Rebel Yell', 'Billy Idol', 1983, 'rock', 'h'],
  ['Total Eclipse of the Heart', 'Bonnie Tyler', 1983, 'pop', 'm'],
  ['Girls Just Want to Have Fun', 'Cyndi Lauper', 1983, 'pop', 'e'],
  ['Sweet Dreams (Are Made of This)', 'Eurythmics', 1983, 'electro', 'e'],
  ['Relax', 'Frankie Goes to Hollywood', 1983, 'electro', 'h'],
  ['Flashdance… What a Feeling', 'Irene Cara', 1983, 'ost', 'm'],
  ['The Trooper', 'Iron Maiden', 1983, 'metal', 'm'],
  ['Sunshine Reggae', 'Laid Back', 1983, 'reggae', 'h'],
  ['All Night Long (All Night)', 'Lionel Richie', 1983, 'funk', 'm'],
  ['99 Luftballons', 'Nena', 1983, 'pop', 'm'],
  ['Blue Monday', 'New Order', 1983, 'electro', 'm'],
  ['Dès que le vent soufflera', 'Renaud', 1983, 'chanson', 'm'],
  ['Every Breath You Take', 'The Police', 1983, 'rock', 'e'],
  ['Sunday Bloody Sunday', 'U2', 1983, 'rock', 'm'],
  ['Red Red Wine', 'UB40', 1983, 'reggae', 'h'],
  ['Jump', 'Van Halen', 1983, 'rock', 'm'],
  ['Big in Japan', 'Alphaville', 1984, 'electro', 'h'],
  ['Femme libérée', 'Cookie Dingler', 1984, 'chanson', 'h'],
  ['You Spin Me Round (Like a Record)', 'Dead or Alive', 1984, 'electro', 'h'],
  ['Careless Whisper', 'George Michael', 1984, 'pop', 'e'],
  ["You're My Heart, You're My Soul", 'Modern Talking', 1984, 'pop', 'h'],
  ['Footloose', 'Kenny Loggins', 1984, 'ost', 'm'],
  ['Marcia Baila', 'Les Rita Mitsouko', 1984, 'rock', 'm'],
  ["What's Love Got to Do with It", 'Tina Turner', 1984, 'pop', 'm'],
  ['Like a Virgin', 'Madonna', 1984, 'pop', 'e'],
  ['Material Girl', 'Madonna', 1984, 'pop', 'm'],
  ['When Doves Cry', 'Prince', 1984, 'funk', 'm'],
  ['Purple Rain', 'Prince', 1984, 'rock', 'e'],
  ['Radio Ga Ga', 'Queen', 1984, 'rock', 'm'],
  ['Ghostbusters', 'Ray Parker Jr.', 1984, 'ost', 'e'],
  ['Un autre monde', 'Téléphone', 1984, 'rock', 'm'],
  ['Last Christmas', 'Wham!', 1984, 'pop', 'e'],
  ['Wake Me Up Before You Go-Go', 'Wham!', 1984, 'pop', 'e'],
  ['Week-end à Rome', 'Étienne Daho', 1984, 'chanson', 'h'],
  ['Take On Me', 'a-ha', 1985, 'pop', 'e'],
  ['Tarzan Boy', 'Baltimora', 1985, 'electro', 'h'],
  ['Money for Nothing', 'Dire Straits', 1985, 'rock', 'm'],
  ['Rock Me Amadeus', 'Falco', 1985, 'pop', 'h'],
  ['Trois nuits par semaine', 'Indochine', 1985, 'rock', 'm'],
  ['Je te donne', 'Jean-Jacques Goldman & Michael Jones', 1985, 'chanson', 'm'],
  ['Macumba', 'Jean-Pierre Mader', 1985, 'chanson', 'h'],
  ['Running Up That Hill (A Deal with God)', 'Kate Bush', 1985, 'pop', 'm'],
  ["Don't You (Forget About Me)", 'Simple Minds', 1985, 'rock', 'm'],
  ['Live Is Life', 'Opus', 1985, 'rock', 'h'],
  ['Partenaire particulier', 'Partenaire Particulier', 1985, 'chanson', 'h'],
  ['Mistral gagnant', 'Renaud', 1985, 'chanson', 'm'],
  ['Everybody Wants to Rule the World', 'Tears for Fears', 1985, 'pop', 'm'],
  ['Take My Breath Away', 'Berlin', 1986, 'ost', 'm'],
  ['Voyage voyage', 'Desireless', 1986, 'electro', 'h'],
  ["Livin' on a Prayer", 'Bon Jovi', 1986, 'rock', 'e'],
  ['The Final Countdown', 'Europe', 1986, 'rock', 'e'],
  ['Ville de lumière', 'Gold', 1986, 'chanson', 'h'],
  ["J'ai vu", 'Niagara', 1986, 'rock', 'h'],
  ["T'en va pas", 'Elsa', 1986, 'chanson', 'h'],
  ['Les Démons de minuit', 'Images', 1986, 'chanson', 'h'],
  ['Danger Zone', 'Kenny Loggins', 1986, 'ost', 'm'],
  ['Andy', 'Les Rita Mitsouko', 1986, 'rock', 'h'],
  ['Master of Puppets', 'Metallica', 1986, 'metal', 'm'],
  ['Libertine', 'Mylène Farmer', 1986, 'chanson', 'm'],
  ['Kiss', 'Prince', 1986, 'funk', 'm'],
  ['There Is a Light That Never Goes Out', 'The Smiths', 1986, 'rock', 'h'],
  ["Sweet Child o' Mine", "Guns N' Roses", 1987, 'rock', 'e'],
  ['Need You Tonight', 'INXS', 1987, 'rock', 'h'],
  ['Là-bas', 'Jean-Jacques Goldman', 1987, 'chanson', 'm'],
  ["(I've Had) The Time of My Life", 'Bill Medley & Jennifer Warnes', 1987, 'ost', 'm'],
  ["Ella, elle l'a", 'France Gall', 1987, 'chanson', 'm'],
  ['Welcome to the Jungle', "Guns N' Roses", 1987, 'rock', 'm'],
  ['Bad', 'Michael Jackson', 1987, 'pop', 'e'],
  ['Smooth Criminal', 'Michael Jackson', 1987, 'pop', 'e'],
  ['Never Gonna Give You Up', 'Rick Astley', 1987, 'pop', 'e'],
  ['Just Like Heaven', 'The Cure', 1987, 'rock', 'm'],
  ['With or Without You', 'U2', 1987, 'rock', 'm'],
  ['Joe le taxi', 'Vanessa Paradis', 1987, 'chanson', 'm'],
  ['I Wanna Dance with Somebody (Who Loves Me)', 'Whitney Houston', 1987, 'pop', 'e'],
  ['Nuit de folie', 'Début de Soirée', 1988, 'electro', 'h'],
  ['She Drives Me Crazy', 'Fine Young Cannibals', 1988, 'pop', 'h'],
  ['One', 'Metallica', 1988, 'metal', 'm'],
  ['The Look', 'Roxette', 1988, 'pop', 'h'],
  ['Wicked Game', 'Chris Isaak', 1989, 'rock', 'h'],
  ['Love Shack', "The B-52's", 1989, 'pop', 'm'],
  ['Casser la voix', 'Patrick Bruel', 1989, 'chanson', 'm'],
  ['Back to Life (However Do You Want Me)', 'Soul II Soul', 1989, 'funk', 'h'],
  ['Pump Up the Jam', 'Technotronic', 1989, 'electro', 'm'],

  // ---------------------------------------------------------------- 1990–1999
  ['Enjoy the Silence', 'Depeche Mode', 1990, 'electro', 'm'],
  ['Né en 17 à Leidenstadt', 'Fredericks Goldman Jones', 1990, 'chanson', 'm'],
  ['Nothing Compares 2 U', "Sinéad O'Connor", 1990, 'pop', 'm'],
  ['(Everything I Do) I Do It for You', 'Bryan Adams', 1991, 'pop', 'm'],
  ["I'm Too Sexy", 'Right Said Fred', 1991, 'pop', 'h'],
  ['November Rain', "Guns N' Roses", 1991, 'rock', 'm'],
  ['Bouge de là', 'MC Solaar', 1991, 'rap', 'm'],
  ['Caroline', 'MC Solaar', 1991, 'rap', 'm'],
  ['Enter Sandman', 'Metallica', 1991, 'metal', 'e'],
  ['Nothing Else Matters', 'Metallica', 1991, 'metal', 'm'],
  ['Désenchantée', 'Mylène Farmer', 1991, 'chanson', 'm'],
  ['Come as You Are', 'Nirvana', 1991, 'rock', 'm'],
  ['Smells Like Teen Spirit', 'Nirvana', 1991, 'rock', 'e'],
  ['Alive', 'Pearl Jam', 1991, 'rock', 'h'],
  ['Losing My Religion', 'R.E.M.', 1991, 'rock', 'm'],
  ['Under the Bridge', 'Red Hot Chili Peppers', 1991, 'rock', 'm'],
  ['Joyride', 'Roxette', 1991, 'pop', 'h'],
  ['All That She Wants', 'Ace of Base', 1992, 'pop', 'h'],
  ['Sweat (A La La La La Long)', 'Inner Circle', 1992, 'reggae', 'h'],
  ["Nuthin' but a 'G' Thang", 'Dr. Dre', 1992, 'rap', 'm'],
  ['Creep', 'Radiohead', 1992, 'rock', 'm'],
  ['Killing in the Name', 'Rage Against the Machine', 1992, 'metal', 'm'],
  ['Rhythm Is a Dancer', 'Snap!', 1992, 'electro', 'm'],
  ['I Will Always Love You', 'Whitney Houston', 1992, 'pop', 'e'],
  ['No Limit', '2 Unlimited', 1993, 'electro', 'h'],
  ['Foule sentimentale', 'Alain Souchon', 1993, 'chanson', 'm'],
  ['Loser', 'Beck', 1993, 'rock', 'h'],
  ['The Rhythm of the Night', 'Corona', 1993, 'electro', 'h'],
  ['What Is Love', 'Haddaway', 1993, 'electro', 'm'],
  ['Je danse le Mia', 'IAM', 1993, 'rap', 'm'],
  ['Macarena', 'Los del Río', 1993, 'latino', 'h'],
  ['Gin and Juice', 'Snoop Dogg', 1993, 'rap', 'm'],
  ['C.R.E.A.M.', 'Wu-Tang Clan', 1993, 'rap', 'm'],
  ['Can You Feel the Love Tonight', 'Elton John', 1994, 'ost', 'm'],
  ['Basket Case', 'Green Day', 1994, 'rock', 'm'],
  ['Hallelujah', 'Jeff Buckley', 1994, 'rock', 'm'],
  ['All I Want for Christmas Is You', 'Mariah Carey', 1994, 'pop', 'e'],
  ['Glory Box', 'Portishead', 1994, 'electro', 'h'],
  ['Cotton Eye Joe', 'Rednex', 1994, 'pop', 'h'],
  ['Juicy', 'The Notorious B.I.G.', 1994, 'rap', 'm'],
  ['Self Esteem', 'The Offspring', 1994, 'rock', 'm'],
  ['Buddy Holly', 'Weezer', 1994, 'rock', 'h'],
  ['California Love', '2Pac', 1995, 'rap', 'm'],
  ['You Oughta Know', 'Alanis Morissette', 1995, 'rock', 'h'],
  ['Army of Me', 'Björk', 1995, 'electro', 'h'],
  ['Da Funk', 'Daft Punk', 1995, 'electro', 'm'],
  ["Gangsta's Paradise", 'Coolio', 1995, 'rap', 'e'],
  ['Be My Lover', 'La Bouche', 1995, 'electro', 'h'],
  ["Don't Look Back in Anger", 'Oasis', 1995, 'rock', 'm'],
  ["Don't Speak", 'No Doubt', 1995, 'rock', 'm'],
  ["Pour que tu m'aimes encore", 'Céline Dion', 1995, 'chanson', 'm'],
  ['Wonderwall', 'Oasis', 1995, 'rock', 'e'],
  ['Children', 'Robert Miles', 1995, 'electro', 'h'],
  ['Boombastic', 'Shaggy', 1995, 'reggae', 'm'],
  ['Born Slippy .NUXX', 'Underworld', 1995, 'electro', 'h'],
  ['Nirvana', 'Doc Gynéco', 1996, 'rap', 'h'],
  ['Killing Me Softly With His Song', 'Fugees', 1996, 'rap', 'e'],
  ['The Beautiful People', 'Marilyn Manson', 1996, 'metal', 'm'],
  ['Wannabe', 'Spice Girls', 1996, 'pop', 'e'],
  ['Firestarter', 'The Prodigy', 1996, 'electro', 'm'],
  ['Sexy Boy', 'Air', 1997, 'electro', 'h'],
  ['Barbie Girl', 'Aqua', 1997, 'pop', 'm'],
  ['Song 2', 'Blur', 1997, 'rock', 'm'],
  ['Tubthumping', 'Chumbawamba', 1997, 'rock', 'h'],
  ['My Heart Will Go On', 'Céline Dion', 1997, 'pop', 'e'],
  ['Around the World', 'Daft Punk', 1997, 'electro', 'm'],
  ["J't'emmène au vent", 'Louise Attaque', 1997, 'chanson', 'm'],
  ['Du hast', 'Rammstein', 1997, 'metal', 'm'],
  ['Block Rockin’ Beats', 'The Chemical Brothers', 1997, 'electro', 'h'],
  ['Bitter Sweet Symphony', 'The Verve', 1997, 'rock', 'm'],
  ['La Nuit je mens', 'Alain Bashung', 1998, 'chanson', 'h'],
  ['…Baby One More Time', 'Britney Spears', 1998, 'pop', 'e'],
  ['Believe', 'Cher', 1998, 'electro', 'm'],
  ['Blue (Da Ba Dee)', 'Eiffel 65', 1998, 'electro', 'm'],
  ['Praise You', 'Fatboy Slim', 1998, 'electro', 'h'],
  ['Freak on a Leash', 'Korn', 1998, 'metal', 'h'],
  ['Doo Wop (That Thing)', 'Lauryn Hill', 1998, 'rnb', 'm'],
  ["I Don't Want to Miss a Thing", 'Aerosmith', 1998, 'rock', 'm'],
  ["Laisse pas traîner ton fils", 'Suprême NTM', 1998, 'rap', 'm'],
  ['Frozen', 'Madonna', 1998, 'electro', 'h'],
  ['La Tribu de Dana', 'Manau', 1998, 'rap', 'h'],
  ['Clandestino', 'Manu Chao', 1998, 'latino', 'm'],
  ['Teardrop', 'Massive Attack', 1998, 'electro', 'h'],
  ['Music Sounds Better with You', 'Stardust', 1998, 'electro', 'h'],
  ['We Like to Party! (The Vengabus)', 'Vengaboys', 1998, 'electro', 'h'],
  ['Tomber la chemise', 'Zebda', 1998, 'chanson', 'm'],
  ['Feeling for You', 'Cassius', 1999, 'electro', 'h'],
  ['My Name Is', 'Eminem', 1999, 'rap', 'm'],
  ['Mambo No. 5 (a Little Bit of…)', 'Lou Bega', 1999, 'latino', 'h'],
  ["Livin' la Vida Loca", 'Ricky Martin', 1999, 'latino', 'm'],
  ["You'll Be in My Heart", 'Phil Collins', 1999, 'ost', 'm'],
  ['Say My Name', "Destiny's Child", 1999, 'rnb', 'm'],
  ['Californication', 'Red Hot Chili Peppers', 1999, 'rock', 'm'],
  ['Smooth', 'Santana', 1999, 'latino', 'h'],
  ['No Scrubs', 'TLC', 1999, 'rnb', 'm'],

  // ---------------------------------------------------------------- 2000–2009
  ['Yellow', 'Coldplay', 2000, 'rock', 'm'],
  ['One More Time', 'Daft Punk', 2000, 'electro', 'e'],
  ['Down with the Sickness', 'Disturbed', 2000, 'metal', 'h'],
  ['In the End', 'Linkin Park', 2000, 'rock', 'e'],
  ["It Wasn't Me", 'Shaggy', 2000, 'reggae', 'm'],
  ["It's My Life", 'Bon Jovi', 2000, 'rock', 'm'],
  ["Rollin' (Air Raid Vehicle)", 'Limp Bizkit', 2000, 'metal', 'm'],
  ['Lady (Hear Me Tonight)', 'Modjo', 2000, 'electro', 'm'],
  ['Ces soirées-là', 'Yannick', 2000, 'rap', 'h'],
  ['Harder, Better, Faster, Stronger', 'Daft Punk', 2001, 'electro', 'm'],
  ['Clint Eastwood', 'Gorillaz', 2001, 'rap', 'm'],
  ['Près de toi', 'Lorie', 2001, 'pop', 'h'],
  ['Me Gustas Tu', 'Manu Chao', 2001, 'latino', 'm'],
  ['Get Ur Freak On', 'Missy Elliott', 2001, 'rap', 'h'],
  ['Le Vent nous portera', 'Noir Désir', 2001, 'rock', 'm'],
  ['Whenever, Wherever', 'Shakira', 2001, 'latino', 'm'],
  ['Chop Suey!', 'System of a Down', 2001, 'metal', 'e'],
  ['Toxicity', 'System of a Down', 2001, 'metal', 'm'],
  ['En apesanteur', 'Calogero', 2002, 'chanson', 'h'],
  ['Clocks', 'Coldplay', 2002, 'rock', 'm'],
  ['Lose Yourself', 'Eminem', 2002, 'rap', 'e'],
  ["Don't Know Why", 'Norah Jones', 2002, 'pop', 'h'],
  ["Parce qu'on vient de loin", 'Corneille', 2002, 'rnb', 'h'],
  ['In da Club', '50 Cent', 2003, 'rap', 'm'],
  ['Crazy in Love', 'Beyoncé', 2003, 'rnb', 'm'],
  ['Where Is the Love?', 'Black Eyed Peas', 2003, 'rap', 'm'],
  ['Toxic', 'Britney Spears', 2003, 'pop', 'e'],
  ['99 Problems', 'Jay-Z', 2003, 'rap', 'h'],
  ['Le Chemin', 'Kyo', 2003, 'rock', 'm'],
  ['Numb', 'Linkin Park', 2003, 'rock', 'e'],
  ['Hey Ya!', 'OutKast', 2003, 'rap', 'e'],
  ['Get Busy', 'Sean Paul', 2003, 'reggae', 'm'],
  ['Mr. Brightside', 'The Killers', 2003, 'rock', 'e'],
  ['Seven Nation Army', 'The White Stripes', 2003, 'rock', 'e'],
  ['Take Me Out', 'Franz Ferdinand', 2004, 'rock', 'm'],
  ['Somewhere Only We Know', 'Keane', 2004, 'rock', 'h'],
  ['Tout le bonheur du monde', 'Sinsemilia', 2004, 'chanson', 'h'],
  ['Duality', 'Slipknot', 2004, 'metal', 'm'],
  ['La Ritournelle', 'Sébastien Tellier', 2004, 'electro', 'h'],
  ['I Bet You Look Good on the Dancefloor', 'Arctic Monkeys', 2005, 'rock', 'm'],
  ['Love Generation', 'Bob Sinclar', 2005, 'electro', 'm'],
  ['Feel Good Inc.', 'Gorillaz', 2005, 'rap', 'e'],
  ['Better Together', 'Jack Johnson', 2005, 'pop', 'h'],
  ['Gold Digger', 'Kanye West', 2005, 'rap', 'm'],
  ['Temperature', 'Sean Paul', 2005, 'reggae', 'm'],
  ['Back to Black', 'Amy Winehouse', 2006, 'rnb', 'm'],
  ['Rehab', 'Amy Winehouse', 2006, 'rnb', 'm'],
  ["Hips Don't Lie", 'Shakira', 2006, 'latino', 'e'],
  ['Crazy', 'Gnarls Barkley', 2006, 'rnb', 'm'],
  ['SexyBack', 'Justin Timberlake', 2006, 'rnb', 'm'],
  ['La Boulette', "Diam's", 2006, 'rap', 'm'],
  ['Supermassive Black Hole', 'Muse', 2006, 'rock', 'm'],
  ['Maneater', 'Nelly Furtado', 2006, 'pop', 'h'],
  ['Chasing Cars', 'Snow Patrol', 2006, 'rock', 'm'],
  ['Love Is Gone', 'David Guetta', 2007, 'electro', 'h'],
  ["On s'attache", 'Christophe Maé', 2007, 'chanson', 'h'],
  ['D.A.N.C.E.', 'Justice', 2007, 'electro', 'h'],
  ['Kids', 'MGMT', 2007, 'electro', 'm'],
  ['Umbrella', 'Rihanna', 2007, 'rnb', 'e'],
  ['Viva la Vida', 'Coldplay', 2008, 'rock', 'e'],
  ['Comme des enfants', 'Cœur de pirate', 2008, 'chanson', 'm'],
  ['Walking on a Dream', 'Empire of the Sun', 2008, 'electro', 'h'],
  ["I'm Yours", 'Jason Mraz', 2008, 'pop', 'h'],
  ['Sex on Fire', 'Kings of Leon', 2008, 'rock', 'm'],
  ['Just Dance', 'Lady Gaga', 2008, 'pop', 'm'],
  ['Poker Face', 'Lady Gaga', 2008, 'pop', 'e'],
  ['I Gotta Feeling', 'Black Eyed Peas', 2009, 'electro', 'e'],
  ['Alors on danse', 'Stromae', 2009, 'electro', 'e'],

  // ---------------------------------------------------------------- 2010–2019
  ['Rolling in the Deep', 'Adele', 2010, 'pop', 'e'],
  ['Time', 'Hans Zimmer', 2010, 'ost', 'm'],
  ['Je veux', 'ZAZ', 2010, 'chanson', 'm'],
  ['Someone Like You', 'Adele', 2011, 'pop', 'm'],
  ['Levels', 'Avicii', 2011, 'electro', 'm'],
  ['Feel So Close', 'Calvin Harris', 2011, 'electro', 'h'],
  ['Call Me Maybe', 'Carly Rae Jepsen', 2011, 'pop', 'm'],
  ['Titanium', 'David Guetta', 2011, 'electro', 'm'],
  ['Somebody That I Used to Know', 'Gotye', 2011, 'pop', 'm'],
  ['Little Talks', 'Of Monsters and Men', 2011, 'rock', 'h'],
  ['We Found Love', 'Rihanna', 2011, 'electro', 'm'],
  ['Latch', 'Disclosure', 2012, 'electro', 'h'],
  ['Radioactive', 'Imagine Dragons', 2012, 'rock', 'm'],
  ["Don't You Worry Child", 'Swedish House Mafia', 2012, 'electro', 'm'],
  ['Let Her Go', 'Passenger', 2012, 'pop', 'h'],
  ['Gangnam Style', 'PSY', 2012, 'pop', 'e'],
  ['Ho Hey', 'The Lumineers', 2012, 'rock', 'h'],
  ['Do I Wanna Know?', 'Arctic Monkeys', 2013, 'rock', 'm'],
  ['Wake Me Up', 'Avicii', 2013, 'electro', 'e'],
  ['Get Lucky', 'Daft Punk', 2013, 'electro', 'e'],
  ['Take Me to Church', 'Hozier', 2013, 'rock', 'm'],
  ['Let It Go', 'Idina Menzel', 2013, 'ost', 'e'],
  ['Dernière danse', 'Indila', 2013, 'chanson', 'm'],
  ['Paris-Seychelles', 'Julien Doré', 2013, 'chanson', 'h'],
  ['Royals', 'Lorde', 2013, 'pop', 'm'],
  ['Bella', 'Maître Gims', 2013, 'rap', 'm'],
  ['Happy', 'Pharrell Williams', 2013, 'pop', 'e'],
  ['Blurred Lines', 'Robin Thicke', 2013, 'rnb', 'm'],
  ['Formidable', 'Stromae', 2013, 'chanson', 'e'],
  ['Papaoutai', 'Stromae', 2013, 'electro', 'e'],
  ['Sur ma route', 'Black M', 2014, 'rap', 'm'],
  ['Christine', 'Christine and the Queens', 2014, 'chanson', 'm'],
  ['Rather Be', 'Clean Bandit', 2014, 'electro', 'h'],
  ['Thinking Out Loud', 'Ed Sheeran', 2014, 'pop', 'm'],
  ['Color Gitano', 'Kendji Girac', 2014, 'chanson', 'h'],
  ['Uptown Funk', 'Mark Ronson', 2014, 'funk', 'e'],
  ['Stay with Me', 'Sam Smith', 2014, 'pop', 'm'],
  ['Chandelier', 'Sia', 2014, 'pop', 'm'],
  ['Blank Space', 'Taylor Swift', 2014, 'pop', 'm'],
  ['Shake It Off', 'Taylor Swift', 2014, 'pop', 'e'],
  ['Hello', 'Adele', 2015, 'pop', 'e'],
  ['Tchikita', 'Jul', 2015, 'rap', 'm'],
  ['Sorry', 'Justin Bieber', 2015, 'pop', 'm'],
  ['Avenir', 'Louane', 2015, 'chanson', 'm'],
  ['Jour 1', 'Louane', 2014, 'chanson', 'm'],
  ['7 Years', 'Lukas Graham', 2015, 'pop', 'h'],
  ["Can't Feel My Face", 'The Weeknd', 2015, 'rnb', 'm'],
  ['Lean On', 'Major Lazer', 2015, 'electro', 'm'],
  ['On verra', 'Nekfeu', 2015, 'rap', 'm'],
  ['The Less I Know the Better', 'Tame Impala', 2015, 'rock', 'm'],
  ['One Dance', 'Drake', 2016, 'rnb', 'e'],
  ["Je m'en vais", 'Vianney', 2016, 'chanson', 'm'],
  ['Cosmo', 'Soprano', 2016, 'rap', 'h'],
  ['Dommage', 'Bigflo & Oli', 2017, 'rap', 'm'],
  ['Reine', 'Dadju', 2017, 'rnb', 'm'],
  ['New Rules', 'Dua Lipa', 2017, 'pop', 'm'],
  ['Shape of You', 'Ed Sheeran', 2017, 'pop', 'e'],
  ['Kid', 'Eddy de Pretto', 2017, 'chanson', 'h'],
  ['HUMBLE.', 'Kendrick Lamar', 2017, 'rap', 'm'],
  ['Despacito', 'Luis Fonsi', 2017, 'latino', 'e'],
  ['Basique', 'Orelsan', 2017, 'rap', 'm'],
  ['Rockstar', 'Post Malone', 2017, 'rap', 'm'],
  ['Balance ton quoi', 'Angèle', 2018, 'chanson', 'm'],
  ['Copines', 'Aya Nakamura', 2018, 'rnb', 'm'],
  ['Djadja', 'Aya Nakamura', 2018, 'rnb', 'e'],
  ['Pookie', 'Aya Nakamura', 2018, 'rnb', 'm'],
  ['This Is America', 'Childish Gambino', 2018, 'rap', 'm'],
  ['La Grenade', 'Clara Luciani', 2018, 'chanson', 'm'],
  ['Ta marinière', 'Hoshi', 2018, 'chanson', 'h'],
  ['Shallow', 'Lady Gaga & Bradley Cooper', 2018, 'ost', 'e'],
  ['Bad Guy', 'Billie Eilish', 2019, 'pop', 'e'],
  ['Say So', 'Doja Cat', 2019, 'rnb', 'm'],
  ['Ciel', 'GIMS', 2019, 'rap', 'm'],
  ['Watermelon Sugar', 'Harry Styles', 2019, 'pop', 'm'],
  ["Don't Start Now", 'Dua Lipa', 2019, 'pop', 'm'],
  ['Au DD', 'PNL', 2019, 'rap', 'm'],
  ['On brûlera', 'Pomme', 2017, 'chanson', 'h'],
  ['Blinding Lights', 'The Weeknd', 2019, 'pop', 'e'],
  ['Dance Monkey', 'Tones and I', 2019, 'pop', 'm'],
  ['Ça va ça vient', 'Vitaa & Slimane', 2019, 'chanson', 'm'],

  // ---------------------------------------------------------------- 2020–
  ['Bande organisée', '13 Organisé', 2020, 'rap', 'e'],
  ['Fever', 'Angèle & Dua Lipa', 2020, 'pop', 'm'],
  ['Doudou', 'Aya Nakamura', 2020, 'rnb', 'm'],
  ['Dákiti', 'Bad Bunny', 2020, 'latino', 'm'],
  ['Coup de vieux', 'Bigflo & Oli', 2020, 'rap', 'h'],
  ['Dynamite', 'BTS', 2020, 'pop', 'm'],
  ['WAP', 'Cardi B', 2020, 'rap', 'm'],
  ['Levitating', 'Dua Lipa', 2020, 'pop', 'm'],
  ['Physical', 'Dua Lipa', 2020, 'pop', 'm'],
  ['Heat Waves', 'Glass Animals', 2020, 'pop', 'm'],
  ['Nous', 'Julien Doré', 2020, 'chanson', 'h'],
  ['Savage', 'Megan Thee Stallion', 2020, 'rap', 'h'],
  ['Le Temps', 'Tayc', 2020, 'rnb', 'm'],
  ['Save Your Tears', 'The Weeknd', 2020, 'pop', 'm'],
  ['Easy On Me', 'Adele', 2021, 'pop', 'm'],
  ['Respire encore', 'Clara Luciani', 2021, 'chanson', 'm'],
  ['Kiss Me More', 'Doja Cat', 2021, 'rnb', 'm'],
  ['Bad Habits', 'Ed Sheeran', 2021, 'pop', 'm'],
  ['Cold Heart (PNAU Remix)', 'Elton John & Dua Lipa', 2021, 'pop', 'm'],
  ['Pepas', 'Farruko', 2021, 'latino', 'h'],
  ['Peaches', 'Justin Bieber', 2021, 'rnb', 'h'],
  ['Industry Baby', 'Lil Nas X', 2021, 'rap', 'm'],
  ['MONTERO (Call Me by Your Name)', 'Lil Nas X', 2021, 'rap', 'm'],
  ["Bruxelles je t'aime", 'Angèle', 2021, 'chanson', 'm'],
  ["L'odeur de l'essence", 'Orelsan', 2021, 'rap', 'm'],
  ["N'y pense plus", 'Tayc', 2021, 'rnb', 'm'],
  ['ZITTI E BUONI', 'Måneskin', 2021, 'rock', 'm'],
  ['La Kiffance', 'Naps', 2021, 'rap', 'm'],
  ['Deja Vu', 'Olivia Rodrigo', 2021, 'pop', 'm'],
  ['Drivers License', 'Olivia Rodrigo', 2021, 'pop', 'm'],
  ['Good 4 U', 'Olivia Rodrigo', 2021, 'pop', 'm'],
  ['La Quête', 'Orelsan', 2021, 'rap', 'm'],
  ['Leave the Door Open', 'Silk Sonic', 2021, 'funk', 'm'],
  ['Petrouchka', 'Soso Maness', 2021, 'rap', 'm'],
  ['Stay', 'The Kid LAROI & Justin Bieber', 2021, 'pop', 'm'],
  ['Me Porto Bonito', 'Bad Bunny', 2022, 'latino', 'm'],
  ['Tití Me Preguntó', 'Bad Bunny', 2022, 'latino', 'm'],
  ['Break My Soul', 'Beyoncé', 2022, 'electro', 'm'],
  ['Mande', 'Gazo & Tiakola', 2022, 'rap', 'm'],
  ['As It Was', 'Harry Styles', 2022, 'pop', 'e'],
  ['Late Night Talking', 'Harry Styles', 2022, 'pop', 'h'],
  ['About Damn Time', 'Lizzo', 2022, 'funk', 'm'],
  ["I'm Good (Blue)", 'David Guetta & Bebe Rexha', 2022, 'electro', 'm'],
  ["L'enfer", 'Stromae', 2022, 'chanson', 'm'],
  ['Calm Down', 'Rema', 2022, 'rnb', 'm'],
  ['Despechá', 'Rosalía', 2022, 'latino', 'm'],
  ['Unholy', 'Sam Smith & Kim Petras', 2022, 'pop', 'm'],
  ['Bad Habit', 'Steve Lacy', 2022, 'rnb', 'h'],
  ['Kill Bill', 'SZA', 2022, 'rnb', 'm'],
  ['Snooze', 'SZA', 2022, 'rnb', 'h'],
  ['Anti-Hero', 'Taylor Swift', 2022, 'pop', 'm'],
  ['Paint The Town Red', 'Doja Cat', 2023, 'rap', 'm'],
  ['Dance The Night', 'Dua Lipa', 2023, 'ost', 'm'],
  ['Seven', 'Jung Kook', 2023, 'pop', 'm'],
  ['Flowers', 'Miley Cyrus', 2023, 'pop', 'e'],
  ['Vampire', 'Olivia Rodrigo', 2023, 'pop', 'm'],
  ['Ella Baila Sola', 'Peso Pluma & Eslabon Armado', 2023, 'latino', 'h'],
  ['Popcorn salé', 'Santa', 2023, 'chanson', 'm'],
  ['Greedy', 'Tate McRae', 2023, 'pop', 'm'],
  ['Lose Control', 'Teddy Swims', 2023, 'rnb', 'm'],
  ['La Symphonie des éclairs', 'Zaho de Sagazan', 2023, 'chanson', 'm'],
  ['Beautiful Things', 'Benson Boone', 2024, 'pop', 'm'],
  ['Birds of a Feather', 'Billie Eilish', 2024, 'pop', 'e'],
  ['Good Luck, Babe!', 'Chappell Roan', 2024, 'pop', 'm'],
  ['360', 'Charli xcx', 2024, 'electro', 'm'],
  ['Too Sweet', 'Hozier', 2024, 'rock', 'm'],
  ['Not Like Us', 'Kendrick Lamar', 2024, 'rap', 'e'],
  ['Die With A Smile', 'Lady Gaga & Bruno Mars', 2024, 'pop', 'e'],
  ['APT.', 'ROSÉ & Bruno Mars', 2024, 'pop', 'e'],
  ['Espresso', 'Sabrina Carpenter', 2024, 'pop', 'e'],
  ['Please Please Please', 'Sabrina Carpenter', 2024, 'pop', 'm'],
  ['A Bar Song (Tipsy)', 'Shaboozey', 2024, 'pop', 'm'],
  ['Kongolese sous BBL', 'Théodora', 2024, 'rap', 'm'],
  ['Ordinary', 'Alex Warren', 2025, 'pop', 'm'],
  ['Abracadabra', 'Lady Gaga', 2025, 'pop', 'm'],
];

/** `Michael Jackson` + `Billie Jean` → `michael-jackson-billie-jean`. */
export function slugify(input: string): string {
  return input
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

export const CATALOGUE: Card[] = ROWS.map(([title, artist, year, genres, difficulty]) => ({
  id: `${slugify(artist)}--${slugify(title)}`,
  title,
  artist,
  year,
  genres: genres.split(' ') as Genre[],
  difficulty: DIFFICULTY[difficulty ?? 'm'],
}));

export const CATALOGUE_BY_ID: ReadonlyMap<string, Card> = new Map(
  CATALOGUE.map((c) => [c.id, c]),
);
